version: '3.3'
services:
  winograd:
    build: .
    image: ${CI_REGISTRY_IMAGE}/winograd:${CI_COMMIT_SHORT_SHA}
    ports:
    - 8092:80
    hostname: winograd
    environment:
    - SERVERNAME=${SERVERNAME}
    - USERNAME=${USERNAME}
    - PASSWORD=${PASSWORD}
    - DB_NAME=${DB_NAME}
    - PORT=${PORT}

  mariadb:
    image: mariadb
    hostname: mariadb
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes: 
    - mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8004:80
    environment:
    - PMA_HOST=${PMA_HOST}

volumes:
  mysql:
#    external: true
