services:
  drm:
    build: .
    image: ${CI_REGISTRY_IMAGE}/drm:${CI_COMMIT_SHORT_SHA}
    ports:
    - 8080:80
    hostname: drm
    environment:
    - SERVERNAME=${SERVERNAME}
    - USERNAME=${USERNAME}
    - PASSWORD=${PASSWORD}
    - DB_NAME=${DB_NAME}
    - PORT=${PORT}
    # volumes: 
    # - /zi/home/juliane.nagel/online_studies/php.ini:/usr/local/etc/php/php.ini

  mariadb:
    image: mariadb
    hostname: mariadb
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes: 
    - mysql_drm:/var/lib/mysql #Not sure about the _drm part - its in the wiki how

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80
    environment:
    - PMA_HOST=${PMA_HOST}

volumes:
  mysql_drm: #Not sure about the _drm part - see above
  # mysql:
  #   external: true
