version: '3.8'

services:
  linguistics:
    # Build from the Dockerfile in the current directory (".")
    build: .
    image: linguistics:latest
    
    # Map host port 8080 to container port 80
    ports:
      - "8080:80"

    # Environment variables (if you have them set locally)
    environment:
      - SERVERNAME=${SERVERNAME}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}

    # Bind-mount your local "linguistics" folder into the container
    # so you can edit locally and see changes without rebuilding.
    volumes:
      - type: bind
        source: "./linguistics"
        target: "/var/www/html"

  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    # Persist MySQL data on a named volume
    volumes: 
      - mysql_linguistics:/var/lib/mysql
    # Expose MySQL to host (optional if you only use phpMyAdmin)
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8000:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306

volumes:
  mysql_linguistics:
