services:
  your_project:
    build: .
    image: ${CI_REGISTRY_IMAGE}/your_project:${CI_COMMIT_SHORT_SHA}
    ports:
    - 8080:80
    hostname: your_project
    environment:
    - SERVERNAME=${SERVERNAME}
    - USERNAME=${USERNAME}
    - PASSWORD=${PASSWORD}
    - DB_NAME=${DB_NAME}
    - PORT=${PORT}

  mariadb:
    image: mariadb
    hostname: mariadb
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
    - mysql_your_project:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
    - 8000:80
    environment:
    - PMA_HOST=${PMA_HOST}

volumes:
  mysql_your_project:
    external: true