// items_mini_q.js

const testItems = [
  { question: "Das Dreieck lehnt das Viereck nicht ab",      shapes: "C-T-S-V", correctAnswer: 0 },  
  { question: "Das Viereck wird vom Dreieck nicht vorgezogen", shapes: "C-S-T-V", correctAnswer: 0 },
  { question: "Der Kreis wird vom Dreieck nicht vorgezogen",    shapes: "C-T-S-V", correctAnswer: 0 },
  { question: "Das Dreieck zieht das Viereck vor",             shapes: "C-S-T-V", correctAnswer: 1 },
  { question: "Der Kreis wird vom Dreieck nicht abgelehnt",    shapes: "V-T-S-C", correctAnswer: 0 },
  { question: "Das Viereck wird vom Dreieck nicht abgelehnt",   shapes: "V-S-T-C", correctAnswer: 0 },
  { question: "Das Dreieck zieht den Kreis nicht vor",         shapes: "V-T-S-C", correctAnswer: 1 },
  { question: "Der Kreis wird vom Dreieck nicht vorgezogen",    shapes: "C-S-T-V", correctAnswer: 1 },
  { question: "Der Kreis wird vom Dreieck vorgezogen",         shapes: "C-S-T-V", correctAnswer: 0 },
  { question: "Das Viereck wird vom Dreieck abgelehnt",        shapes: "V-T-S-C", correctAnswer: 0 },  
  { question: "Das Dreieck zieht das Viereck nicht vor",      shapes: "C-T-S-V", correctAnswer: 1 },
  { question: "Das Dreieck zieht den Kreis nicht vor",         shapes: "C-T-S-V", correctAnswer: 0 },
  { question: "Der Kreis wird vom Dreieck abgelehnt",         shapes: "V-T-S-C", correctAnswer: 1 },
  { question: "Das Dreieck lehnt das Viereck nicht ab",        shapes: "V-S-T-C", correctAnswer: 0 },
  { question: "Das Dreieck zieht den Kreis vor",              shapes: "V-T-S-C", correctAnswer: 0 },
  { question: "Das Dreieck lehnt den Kreis ab",               shapes: "V-T-S-C", correctAnswer: 0 }, 
  { question: "Das Viereck wird vom Dreieck vorgezogen",       shapes: "C-T-S-V", correctAnswer: 0 },
  { question: "Das Dreieck zieht das Viereck nicht vor",      shapes: "C-S-T-V", correctAnswer: 0 },
  { question: "Das Viereck wird vom Dreieck nicht vorgezogen", shapes: "C-T-S-V", correctAnswer: 1 },
  { question: "Das Dreieck zieht das Viereck nicht vor",      shapes: "V-S-T-C", correctAnswer: 1 },
  { question: "Das Viereck wird vom Dreieck vorgezogen",       shapes: "C-S-T-V", correctAnswer: 1 },
  { question: "Das Dreieck zieht das Viereck vor",             shapes: "V-T-S-C", correctAnswer: 1 }, 
  { question: "Das Viereck wird vom Dreieck abgelehnt",        shapes: "C-S-T-V", correctAnswer: 0 },
  { question: "Das Dreieck zieht den Kreis vor",              shapes: "C-T-S-V", correctAnswer: 1 },
  { question: "Das Viereck wird vom Dreieck abgelehnt",        shapes: "V-S-T-C", correctAnswer: 1 },
  { question: "Das Dreieck lehnt das Viereck nicht ab",        shapes: "V-T-S-C", correctAnswer: 1 },
  { question: "Das Dreieck lehnt das Viereck nicht ab",        shapes: "C-S-T-V", correctAnswer: 1 },
  { question: "Das Viereck wird vom Dreieck nicht abgelehnt",   shapes: "C-T-S-V", correctAnswer: 0 },
  { question: "Das Viereck wird vom Dreieck nicht abgelehnt",   shapes: "C-S-T-V", correctAnswer: 1 },
  { question: "Das Dreieck zieht den Kreis nicht vor",         shapes: "V-S-T-C", correctAnswer: 0 },
  { question: "Das Dreieck zieht das Viereck vor",             shapes: "V-S-T-C", correctAnswer: 1 },
  { question: "Das Dreieck lehnt den Kreis ab",               shapes: "C-S-T-V", correctAnswer: 0 }, 
  { question: "Der Kreis wird vom Dreieck nicht abgelehnt",    shapes: "C-S-T-V", correctAnswer: 0 },
  { question: "Der Kreis wird vom Dreieck abgelehnt",         shapes: "V-S-T-C", correctAnswer: 0 },  
  { question: "Das Dreieck lehnt das Viereck ab",             shapes: "V-S-T-C", correctAnswer: 1 },
  { question: "Das Viereck wird vom Dreieck nicht vorgezogen", shapes: "V-T-S-C", correctAnswer: 1 },
  { question: "Das Dreieck lehnt den Kreis ab",               shapes: "V-S-T-C", correctAnswer: 0 },
  { question: "Der Kreis wird vom Dreieck vorgezogen",         shapes: "C-T-S-V", correctAnswer: 1 },
  { question: "Das Dreieck zieht den Kreis vor",              shapes: "V-S-T-C", correctAnswer: 1 },
  { question: "Das Dreieck lehnt das Viereck ab",             shapes: "C-S-T-V", correctAnswer: 0 },
  { question: "Das Dreieck zieht den Kreis vor",              shapes: "C-S-T-V", correctAnswer: 1 },
  { question: "Das Viereck wird vom Dreieck abgelehnt",        shapes: "C-T-S-V", correctAnswer: 1 },
  { question: "Der Kreis wird vom Dreieck vorgezogen",         shapes: "V-S-T-C", correctAnswer: 1 },
  { question: "Der Kreis wird vom Dreieck nicht vorgezogen",    shapes: "V-S-T-C", correctAnswer: 0 },
  { question: "Der Kreis wird vom Dreieck abgelehnt",         shapes: "C-S-T-V", correctAnswer: 1 },
  { question: "Das Dreieck zieht das Viereck vor",             shapes: "C-T-S-V", correctAnswer: 0 },
  { question: "Das Viereck wird vom Dreieck nicht vorgezogen", shapes: "V-S-T-C", correctAnswer: 0 },
  { question: "Der Kreis wird vom Dreieck nicht abgelehnt",    shapes: "V-T-S-C", correctAnswer: 1 },
  { question: "Das Dreieck lehnt den Kreis nicht ab",         shapes: "V-T-S-C", correctAnswer: 1 },
  { question: "Das Viereck wird vom Dreieck vorgezogen",       shapes: "V-T-S-C", correctAnswer: 1 },
  { question: "Das Dreieck zieht das Viereck nicht vor",      shapes: "V-T-S-C", correctAnswer: 0 }, 
  { question: "Der Kreis wird vom Dreieck nicht abgelehnt",    shapes: "V-T-S-C", correctAnswer: 1 },  
];
